# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


trigger:
- master

pool:
  vmImage: 'win1803'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'DCD-CFT-VH-Pilot'
  KeyVaultName: 'vhhearingsapiatpilot'
  SecretsFilter: 'TenantId,HearingsApiResourceId,clientId,ClientSecret'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.401'
  inputs:
    version: 2.1.401
      
- script: dotnet publish -c $(buildConfiguration) -r win10-x64
  displayName: 'dotnet build $(buildConfiguration)'

- task: AzureKeyVault@1
  displayName: 'Azure Key Vault: $(KeyVaultName)'
  inputs:
    azureSubscription: '$(azureSubscription)'
    KeyVaultName: '$(KeyVaultName)'
    SecretsFilter: '$(SecretsFilter)'

- powershell: |
    $tokenGeneratorPath = ((Get-ChildItem -Recurse ADTokenGenerator.exe).directoryname)
    $authority = 'https://login.microsoftonline.com/' + '$(TenantId)'
    $clientId = '$(clientId)'
    $clientSecret = '$(ClientSecret)'
    $resourceId = '$(HearingsApiResourceId)'

    Set-Location $(Build.SourcesDirectory)\bin\Release\netcoreapp2.1\win10-x64\publish
    $token = & .\ADTokenGenerator.exe $authority $clientId $clientSecret $resourceId

    Write-Output "----------------------------"
    Write-Output ""
    Write-Output $token
    Write-Output ""
    Write-Output "----------------------------"
