# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'win1803'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish -c $(buildConfiguration) -r win10-x64
  displayName: 'dotnet build $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\bin\Release\netcoreapp2.1\win10-x64'
    ArtifactName: tokengenerator